"""update

Revision ID: 18f8eeb5938c
Revises: b6aec9715b77
Create Date: 2024-03-23 21:50:55.115898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f8eeb5938c'
down_revision = 'b6aec9715b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
