"""update

Revision ID: 1ede61404e17
Revises: 18f8eeb5938c
Create Date: 2024-03-23 21:51:13.708615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ede61404e17'
down_revision = '18f8eeb5938c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
